name: speech_to_gpt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi=0.*.*
  - uvicorn=0.*.*
  - python-multipart = 0.0.*
  - transformers=4.*.*
  - pytorch
  - deepspeed
  - ollama
  - tenacity
  - pip
  - ruff
  - python-jose
  - passlib
  - sqlalchemy
  - sqlalchemy-utils
  - langchain
  - phidata
  - chromadb
platforms:
  - linux-64
